// <auto-generated />
using System;
using Aula04.RazorPages.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aula04.RazorPages.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230912020421_CreateDatabase")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("Aula04.RazorPages.Model.AlunoModel", b =>
                {
                    b.Property<int?>("IdAluno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataInscricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeAluno")
                        .HasColumnType("TEXT");

                    b.HasKey("IdAluno");

                    b.ToTable("Alunos", (string)null);
                });

            modelBuilder.Entity("Aula04.RazorPages.Model.CursoModel", b =>
                {
                    b.Property<int?>("IdCurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataTermino")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeCurso")
                        .HasColumnType("TEXT");

                    b.HasKey("IdCurso");

                    b.ToTable("Cursos", (string)null);
                });

            modelBuilder.Entity("CursoAluno", b =>
                {
                    b.Property<int>("IdCurso")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdAluno")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdCurso", "IdAluno");

                    b.HasIndex("IdAluno");

                    b.ToTable("CursoAluno", (string)null);
                });

            modelBuilder.Entity("CursoAluno", b =>
                {
                    b.HasOne("Aula04.RazorPages.Model.AlunoModel", null)
                        .WithMany()
                        .HasForeignKey("IdAluno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aula04.RazorPages.Model.CursoModel", null)
                        .WithMany()
                        .HasForeignKey("IdCurso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
